/** Channel names for the settings window. Re-exported from ipc.ts; see the note there. */
export const SETTINGS_CH = {
  get: 'settings:get',
  set: 'settings:set',
  changed: 'settings:changed',
  status: 'status:get',
  statusChanged: 'status:changed',
  setEnabled: 'app:setEnabled',
  preview: 'app:preview',
  previewEmote: 'app:previewEmote',
  emoteImport: 'emote:import',
  emoteRemove: 'emote:remove',
  about: 'app:about',
  openFolder: 'app:openSettingsFolder',
  openProject: 'app:openProjectPage',
  retryHelper: 'app:retryHelper',
  capture: 'app:capture',
  openAccessibility: 'app:openAccessibility',
  roomGet: 'room:get',
  roomChanged: 'room:state',
  roomCreate: 'room:create',
  roomJoin: 'room:join',
  roomLeave: 'room:leave',
  roomMute: 'room:mute',
  roomClipboard: 'room:clipboardCode',
  roomCopy: 'room:copyCode',
  roomRetryInternet: 'room:retryInternet',
  showSection: 'settings:showSection',
} as const;
